const guestForm = document.getElementById('guest-form');

export const elements = {
  guestForm,
  guestNameInput: document.getElementById('guest-name'),
  guestNameCounter: document.getElementById('guest-name-counter'),
  memoryTextInput: document.getElementById('memory-text'),
  memoryTextCounter: document.getElementById('memory-text-counter'),
  memoryImageInput: document.getElementById('memory-image'),
  formMessage: document.getElementById('form-message'),
  previewName: document.getElementById('preview-name'),
  previewDate: document.getElementById('preview-date'),
  previewText: document.getElementById('preview-text'),
  previewImage: document.getElementById('preview-image'),
  previewImageWrap: document.getElementById('preview-image-wrap'),
  galleryGrid: document.getElementById('gallery-grid'),
  galleryActions: document.getElementById('gallery-actions'),
  galleryLoadMoreButton: document.getElementById('gallery-load-more'),
  galleryLoadMoreStatus: document.getElementById('gallery-load-more-status'),
  galleryLoadMoreSentinel: document.getElementById('gallery-load-more-sentinel'),
  submitButton: guestForm.querySelector('button[type="submit"]'),

  galleryLightbox: document.getElementById('gallery-lightbox'),
  galleryLightboxCard: document.getElementById('gallery-lightbox-card'),
  galleryLightboxBackdrop: document.getElementById('gallery-lightbox-backdrop'),
  galleryLightboxClose: document.getElementById('gallery-lightbox-close'),
  galleryLightboxPrev: document.getElementById('gallery-lightbox-prev'),
  galleryLightboxNext: document.getElementById('gallery-lightbox-next'),
  galleryLightboxImage: document.getElementById('gallery-lightbox-image'),
  galleryLightboxStatus: document.getElementById('gallery-lightbox-status'),
  galleryLightboxAuthor: document.getElementById('gallery-lightbox-author'),
  galleryLightboxDate: document.getElementById('gallery-lightbox-date'),
  galleryLightboxMessage: document.getElementById('gallery-lightbox-message'),
  galleryLightboxCount: document.getElementById('gallery-lightbox-count'),
};