const guestForm = document.getElementById('guest-form');

export const elements = {
  guestForm,
  guestNameInput: document.getElementById('guest-name'),
  guestNameCounter: document.getElementById('guest-name-counter'),
  memoryTextInput: document.getElementById('memory-text'),
  memoryTextCounter: document.getElementById('memory-text-counter'),
  memoryImageInput: document.getElementById('memory-image'),
  formMessage: document.getElementById('form-message'),
  submissionStatus: document.getElementById('submission-status'),
  previewName: document.getElementById('preview-name'),
  previewDate: document.getElementById('preview-date'),
  previewText: document.getElementById('preview-text'),
  previewImage: document.getElementById('preview-image'),
  previewVideo: document.getElementById('preview-video'),
  previewImageWrap: document.getElementById('preview-image-wrap'),
  storiesRail: document.getElementById('stories-rail'),
  galleryGrid: document.getElementById('gallery-grid'),
  galleryActions: document.getElementById('gallery-actions'),
  galleryLoadMoreButton: document.getElementById('gallery-load-more'),
  galleryLoadMoreStatus: document.getElementById('gallery-load-more-status'),
  galleryLoadMoreSentinel: document.getElementById('gallery-load-more-sentinel'),
  submitButton: guestForm.querySelector('button[type="submit"]'),
  successModal: document.getElementById('success-modal'),
  successModalBackdrop: document.getElementById('success-modal-backdrop'),
  successModalClose: document.getElementById('success-modal-close'),
  successModalTitle: document.getElementById('success-modal-title'),
  successModalCopy: document.getElementById('success-modal-copy'),
  successModalPreview: document.getElementById('success-modal-preview'),
  successModalImage: document.getElementById('success-modal-image'),
  successModalVideo: document.getElementById('success-modal-video'),
  successModalMessage: document.getElementById('success-modal-message'),
  successModalGallery: document.getElementById('success-modal-gallery'),
  successModalAnother: document.getElementById('success-modal-another'),

  storiesViewer: document.getElementById('stories-viewer'),
  storiesViewerBackdrop: document.getElementById('stories-viewer-backdrop'),
  storiesViewerClose: document.getElementById('stories-viewer-close'),
  storiesViewerPrev: document.getElementById('stories-viewer-prev'),
  storiesViewerNext: document.getElementById('stories-viewer-next'),
  storiesViewerProgress: document.getElementById('stories-viewer-progress'),
  storiesViewerImage: document.getElementById('stories-viewer-image'),
  storiesViewerVideo: document.getElementById('stories-viewer-video'),
  storiesViewerAuthor: document.getElementById('stories-viewer-author'),
  storiesViewerDate: document.getElementById('stories-viewer-date'),
  storiesViewerCount: document.getElementById('stories-viewer-count'),
  storiesViewerMessage: document.getElementById('stories-viewer-message'),

  galleryLightbox: document.getElementById('gallery-lightbox'),
  galleryLightboxCard: document.getElementById('gallery-lightbox-card'),
  galleryLightboxBackdrop: document.getElementById('gallery-lightbox-backdrop'),
  galleryLightboxClose: document.getElementById('gallery-lightbox-close'),
  galleryLightboxPrev: document.getElementById('gallery-lightbox-prev'),
  galleryLightboxNext: document.getElementById('gallery-lightbox-next'),
  galleryLightboxImage: document.getElementById('gallery-lightbox-image'),
  galleryLightboxVideo: document.getElementById('gallery-lightbox-video'),
  galleryLightboxStatus: document.getElementById('gallery-lightbox-status'),
  galleryLightboxAuthor: document.getElementById('gallery-lightbox-author'),
  galleryLightboxDate: document.getElementById('gallery-lightbox-date'),
  galleryLightboxMessage: document.getElementById('gallery-lightbox-message'),
  galleryLightboxCount: document.getElementById('gallery-lightbox-count'),

  adminPanel: document.getElementById('admin-panel'),
  adminToggle: document.getElementById('admin-toggle'),
  adminBody: document.getElementById('admin-body'),
  adminLogin: document.getElementById('admin-login'),
  adminTools: document.getElementById('admin-tools'),
  adminEmail: document.getElementById('admin-email'),
  adminPassword: document.getElementById('admin-password'),
  adminTurnstileContainer: document.getElementById('admin-turnstile-container'),
  adminUnlock: document.getElementById('admin-unlock'),
  adminRefresh: document.getElementById('admin-refresh'),
  adminLogout: document.getElementById('admin-logout'),
  adminStatus: document.getElementById('admin-status'),
  adminList: document.getElementById('admin-list'),
};