export const CONFIG = {
  supabaseUrl: 'https://nwqdxnubaltoojvfpkwu.supabase.co',
  supabaseAnonKey: 'sb_publishable_OMDf1TtpQV_3hf51J7GnZQ_Cn0t6Pl7',
  eventSlug: 'CamientoNathiyAgus',
  storageBucket: 'wedding-memories',
  galleryPageSize: 12,
  galleryRealtimeChannelName: 'memories-live',
  galleryRealtimeDebounceMs: 500,
  galleryLoadMoreSkeletonCount: 3,
  galleryInfiniteScrollRootMargin: '320px 0px',
  draftStorageKey: 'wedding-memory-draft',
  draftSaveDebounceMs: 300,
  allowedImageTypes: ['image/jpeg', 'image/png', 'image/webp'],
  allowedImageExtensions: ['jpg', 'jpeg', 'png', 'webp'],
  maxImageMb: 6,
  maxImageBytes: 6 * 1024 * 1024,
  maxNameLength: 32,
  minNameLength: 2,
  maxMessageLength: 500,
};