export const CONFIG = {
  supabaseUrl: 'https://iytkpqiwggnjvuwnkarh.supabase.co',
  supabaseAnonKey: 'sb_publishable_u-ynaEolQNugzNRv2cm-Tw_qfNZxnB_',
  eventSlug: 'CamientoNathiyAgus',
  storageBucket: 'wedding-memories',
  galleryPageSize: 12,
  galleryRealtimeChannelName: 'memories-live',
  galleryRealtimeDebounceMs: 500,
  galleryLoadMoreSkeletonCount: 3,
  galleryInfiniteScrollRootMargin: '320px 0px',
  draftStorageKey: 'wedding-memory-draft',
  draftSaveDebounceMs: 300,
  allowedImageTypes: ['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif'],
  allowedVideoTypes: ['video/mp4', 'video/webm', 'video/quicktime'],
  allowedImageExtensions: ['jpg', 'jpeg', 'png', 'webp', 'heic', 'heif'],
  allowedVideoExtensions: ['mp4', 'webm', 'mov'],
  allowedMediaExtensions: ['jpg', 'jpeg', 'png', 'webp', 'heic', 'heif', 'mp4', 'webm', 'mov'],
  maxImageMb: 6,
  maxImageBytes: 6 * 1024 * 1024,
  maxVideoMb: 35,
  maxVideoBytes: 35 * 1024 * 1024,
  compressionTargetMb: 1.6,
  compressionTargetBytes: Math.round(1.6 * 1024 * 1024),
  compressionMaxDimension: 2200,
  compressionInitialQuality: 0.86,
  compressionMinQuality: 0.58,
  storiesMaxItems: 12,
  storyDurationMs: 5000,
  maxNameLength: 32,
  minNameLength: 2,
  maxMessageLength: 500,
};